### ISSUE TITLE
setDimensions sets height based on first slide

### ISSUE THREAD

**Issue by raphaelkottakal** [FormidableLabs/nuka-carousel#126]
With slides of varying height, the setDimensions should go through all the slide heights. Currently it's just getting firstSlide.offsetHeight. This hides the slides that are taller then the first one as overflow. setDimensions function on Line 639

**Comment by aij** [comment]
I'd like to fix this since it is affecting us. Is there a preferred solution?

Some alternatives that come to mind are:

1. Setting the height to the max height of all children.
2. Let the browser compute the height automatically. (Seems to require removing `position: absolute` on slides.)
3. Allow the user to override the slideHeight. (Supporting `'auto'` requires same as above.)

I took a quick stab at 3, but removing `position:absolute` results in some weirdness... See https://github.com/aij/nuka-carousel/commit/3ea4c7830b9e5023140585fe06604de22783a713

I'd prefer to avoid spending too much time going down that road if an entirely different approach would be preferable.

**Comment by kenwheeler** [comment]
Ok if you want to do it, provide a prop called `heightMode`. Make the valid options `adaptive` & `max` and default to `max`.

`max` takes the tallest slide, and checks and sets on every change. `adaptive` sets the height to the height of the tallest slide.

**Comment by aij** [comment]
So, to be clear, both `max` and `adaptive` use the height of the tallest slide, but `max` checks on every change whereas `adaptive` checks less frequently? How much less frequently?

**Comment by aij** [comment]
Hmm, actually, I'm guessing what you mean is that both will check on every call to setDimensions, but `max` will only grow the slideHeight whereas `adaptive` will also shrink it.

**Comment by kenwheeler** [comment]
Indeed

**Comment by jonathan-stone** [comment]
Will this change be published on npm anytime soon?
