### ISSUE TITLE
Provide higher-order component for ControllerMixin

### ISSUE THREAD

**Issue by menelaos** [FormidableLabs/nuka-carousel#16]
Would it be possible to wrap the ControllerMixin functionality into a higher-order component?

**Comment by t128** [comment]
There are a few WTFs/non-react-way things about nuka-carousel. That's one of them.

my solutions looks like this:

```js
import React from 'react';
import Carousel from 'nuka-carousel';

export default React.createClass({
	displayName: 'MyCarousel',

	onChange() {
		let data = this.refs.carousel;

		console.log(data);
	},

	render() {
		return (
			<Carousel
				decorators={[]}
				ref="carousel"
				data={this.onChange}
				>
				<img src="http://placehold.it/1000x300/ffffff/c0392b/&text=slide1"/>
				<img src="http://placehold.it/1000x300/ffffff/c0392b/&text=slide2"/>
				<img src="http://placehold.it/1000x300/ffffff/c0392b/&text=slide3"/>
				<img src="http://placehold.it/1000x300/ffffff/c0392b/&text=slide4"/>
				<img src="http://placehold.it/1000x300/ffffff/c0392b/&text=slide5"/>
				<img src="http://placehold.it/1000x300/ffffff/c0392b/&text=slide6"/>
			</Carousel>
		);
	},
});
```

Now you can [pass the data](http://stackoverflow.com/questions/26176519/reactjs-call-parent-function) to the parent componenet.

**Comment by agroves333** [comment]
The ControllerMixin isn't really necessary at all. It simply adds a method to your existing Carousel wrapper that in turn, adds a ref to your state based on what you set your ref too. Seems a bit unnecessary since React supports (and recommends in favor of) ref callback attributes over string refs.

https://facebook.github.io/react/docs/more-about-refs.html

With this said, HOC would be just as unnecessary as well IMO.

Here's my solution in ES6 syntax that assigns the carousel ref as a class member variable:
```
class App extends React.Component {

    constructor(props) {
        this.carousels = {};
    }

    render() {
        return (
            <Carousel ref={(ref) => this.carousels.carousel = ref}>
            ...
            </Carousel>
            {this.carousels.carousel && (<button type="button" onClick={this.carousels.carousel.goToSlide(5)}>
            Go to slide 5</button>)}
        )
    }
}
```
