### ISSUE TITLE
Is that hardcoded style tag for slide images needed?

### ISSUE THREAD

**Issue by igorsantos07** [FormidableLabs/nuka-carousel#182]
I'm not using images on my slides - nor the original decorators - and I found on the generated code a [weird style tag](https://github.com/FormidableLabs/nuka-carousel/blob/master/src/carousel.js#L818) that doesn't make much sense... It feels more like a CSS rule related to the samples?
I wonder if there could be an option to disable it? Or maybe the original code could verify if there's an image in between its direct children and add the style if needed?

`<style type="text/css">.slider-slide > img {width: 100%; display: block;}</style>`

**Comment by kenwheeler** [comment]
Most people who use the slider libs forget to add it and then complain that the slider isn't working so I coded it in. Would happily accept a PR for an option to turn it off.

**Comment by igorsantos07** [comment]
Will happily send the PR as fast as you replied to this issue. omg! hahaha

**Comment by FoxWhite** [comment]
Hardcoded styles are a total pain in the ass if you want to do ANY styling.....
I'm trying to style the navigation dots (the black color doesn't suit everybody) and the only way that is possible is by re-writing the total decorator by hand. There aren't even active classes applied to active dots so that I could overwrite the defaults with css

**Comment by igorsantos07** [comment]
Agreed @FoxWhite, but please don't pollute the thread with a tangentially related subject. Open a new issue instead :)
