### ISSUE TITLE
framePadding changes frame margin instead of padding

### ISSUE THREAD

**Issue by martinstuecklschwaiger** [FormidableLabs/nuka-carousel#314]
The prop `framePadding` sets the padding `margin` of `.slider-frame` and not the padding. 

Would it be possible to change that to padding? Maybe also to add another prop, so that there is one prop `framePadding` and another one `frameMargin`? 

Using margin instead of padding causes problems when using `box-shadow` (because of `overflow: hidden`). 

If you like the idea, I can also contribute the change myself and write a pull request.

**Comment by alexlande** [comment]
I'm not sure if we can change this. If we use padding instead of margin, the frame list slides through the carousel would be visible in the padded area, so the edges of the next and previous slides would display when you didn't intend them to:

![localhost_8080_](https://user-images.githubusercontent.com/808159/39019226-6beb2c4e-43dd-11e8-98df-2bb23fee595a.png)

We would also have to account for the padding when measuring the frame, which probably wouldn't be possible because we take a style string for this prop rather than a number.

Hard to say without seeing the problem you're hitting with box shadows, but as a workaround I'd suggest applying padding to the slider element by passing a `className` to `Carousel`.

Going to close this, but will reopen if you want to discuss more 👍
