### ISSUE TITLE
debounce/throttle window.onresize event handler

### ISSUE THREAD

**Issue by stefanduberg** [FormidableLabs/nuka-carousel#4]
Would probably be best to debounce/throttle the window.onresize event handler for better performance: https://github.com/kenwheeler/nuka-carousel/blob/954f616962d71c42878a73485a6ceef6505970c3/src/carousel.js#L396

Thoughts?

**Comment by kenwheeler** [comment]
Sure thing, wanna PR, or do you want me to do it?

**Comment by mattfysh** [comment]
@kenwheeler if you have time? 🙏

**Comment by ashika01** [comment]
I’m closing this issue because it has been inactive for long time and is outdated. This probably means that it is not reproducible or it has been fixed in a newer version.

Please open a new issue if you encounter this issue with the latest version. Please use the issue template while opening. Thank you!
