### ISSUE TITLE
when click next button quickly, there is infinite animation

### ISSUE THREAD

**Issue by DualWield** [FormidableLabs/nuka-carousel#427]
# Bugs and Questions

### Prerequisites

**Feel free to delete this section if you have checked off all of the following.**

- [x] I've searched open [issues](https://github.com/FormidableLabs/nuka-carousel/issues) to make sure I'm not opening a duplicate issue
- [x] I have read through the docs before asking a question
- [x] I am using the latest version of nuka-carousel

### Describe Your Environment

- What version of nuka-carousel are you using?
4.4.1
- What version of React are you using?
16.5.2
- What browser are you using?
chrome
- What machine are you on?
mac

### Describe the Problem
When click next button quickly twice, the slider move around, never stop.
https://codesandbox.io/s/2vnmkr2wry

**Expected behavior:**  quickly move to index 2 slide.
**Actual behavior:**  move around and never stop
![test](https://user-images.githubusercontent.com/4132470/46947148-8048b100-d0ac-11e8-9042-96cfec068ff9.gif)

**Comment by dennishansen** [comment]
Also experiencing this issue. Sort of a deal breaker :/

**Comment by ElreyB** [comment]
@DualWield thanks for bringing this up. What is happening here is that react is batching the state of your App component and the state of nuka-carousel. React does this for performance optimization. So when you tap the next button quickly twice your App component and nuka-carousel component slideIndexes are not sync. For this case you would want to update asynchronously as mention in the React docs

https://reactjs.org/docs/state-and-lifecycle.html#state-updates-may-be-asynchronous

```
<Carousel
        slideIndex={this.state.slideIndex}
        afterSlide={slideIndex => this.setState((prevState) => ({slideIndex: prevState.slideIndex + 1}))}
      >
```

However, since nuka-carousel applies `this.props.slideIndex` to `this.state.currentSlide` internally I would recommend this solution

```
  <Carousel
        slideIndex={this.state.slideIndex}
        afterSlide={slideIndex => this.setState({ currentSlide: slideIndex })}
      >
```
I have notice that in the example in the README that it is not written this way. We will look into update the README to reflect this or code base to allow `this.setState({slideIndex})`.
Let us know if this was helpful. Happy coding!

**Comment by CharlyJazz** [comment]
I think this needs a solution inside the internal nuka API. It's a weird behavior that nobody wants to have on their web pages.
