### ISSUE TITLE
Is there an efficient way of dynamically rendering the props of the Carousel based on browser window size?

### ISSUE THREAD

**Issue by clayhan** [FormidableLabs/nuka-carousel#482]
Right now I'm rendering different carousels for different page sizes:

![capture](https://user-images.githubusercontent.com/8486877/51359047-ca11b080-1a7a-11e9-8824-138dd617eb92.PNG)

This is incredibly slow and I was hoping that I can somehow update the slidesToShow and slidesToScroll properties dynamically based on viewport sizes. Right now I am essentially rendering 3 carousels onto the page when I feel there must be a way to get away with rendering just one carousel.

Thanks a ton for you time!

**Comment by sarmeyer** [comment]
Hi @clayhan - Yes, This could be done a couple different ways I think. You can set your slidesToShow and slidesToScroll value on `this.state` and have a method that handles what the value is based on the minWidth/maxWidth values you have defined in your example. You could also create a`getSlidesToScroll/Show` method that takes in the min and maxWidth and returns the value you want for the slidesToScroll/Show props. A switch statement would make this possible and straight forward.

Let me know if either of these works for you! Thanks

**Comment by clayhan** [comment]
@sarmeyer This definitely makes sense but I'm actually trying to AVOID using the viewport influenced logic so I don't have to implement a function that is constantly checking for window size on resize. If this is the only way, I'll def go that route, was just hoping there was some other cool way that my thick skull hasn't thought of 🤣

**Comment by sarmeyer** [comment]
@clayhan I see - Nuka doesn't handle this, unfortunately. If I'm understanding correctly, you could have three Carousel components each with a different className, and then in CSS you could use media queries to give these classNames different styles (ie. display: none) and effectively hide the carousel before it's rendered. This would take the logic out of the JS and be a bit more efficient. Otherwise, if you have a method in the JS, I would suggest using debounce to improve the efficiency of when/how often it's called on resize. Hope this helps!
