### ISSUE TITLE
Flash after wrap around

### ISSUE THREAD

**Issue by ghost** [FormidableLabs/nuka-carousel#494]
- nuka-carousel: ^4.4.7
- react: ^16.7.0, react-dom: ^16.7.0
- Chrome Version 71.0.3578.98
- Surface Book 2

##Problem

https://codesandbox.io/s/3r8110mwlp

**Expected behavior:** Carousel goes slide 1 ,slide 2 , slide 3, slide 1 seamlessly 
**Actual behavior:** After slide 3, carousel returns to slide 1 but flashes 

### Additional Information
Looks like slide 1 goes to -4500px and jumps to 0px when performing the wrap around

**Comment by urqpdykx** [comment]
A workaround is to set the background of .slider to the first image with background cover, however I don't know if this is the best solution

**Comment by selvesandev** [comment]
same problem.

**Comment by sarmeyer** [comment]
I can verify it in the sandbox, but not locally - I'll keep looking into this and let you know if I need more info to reproduce.

**Comment by arkadiuszizycki** [comment]
What is the status? Is there some good workaround?

**Comment by juanmardefago** [comment]
I think I stumbled into something that might help fix this while implementing a new transition for nuka.

When in scroll mode (at least), the first slide and the last slide are actually not close at all, but rather on the opposite ends of the slider-list container (for example left -700 and left 700), so when you actually go from the last slide to the first, it has to jump from left -700 to left 700, hence making this blink effect.

This was extremely evident while I implemented the scroll 3d transition, since I added a css transition for the left position (trasition: left 0.4s ease-out) and each time I went from the last slide to the first, it produced a really long transition jump that did not happen on the other slides.

I think the only way to fix this would be to modify how target position is calculated on scroll (and probably fade) transition modes. That's what I did on the scroll3d transition, and the blinking doesn't happen there, but then again, the target position is calculated in a completely different manner, and I'm still working to fix some bugs.

**Comment by albertwalicki** [comment]
Anything new here? I have the same problem

**Comment by proka89** [comment]
Same problem :( 
nuka-carousel: "4.5.2"

**Comment by clementAC** [comment]
Unfortunately I have the same problem :cry: 
nuka-carousel: "4.5.2"

@juanmardefago do you have some infos to share? I tried the scroll3D animation on codepen and wrapAround behavior is not like other animations. You "fixed" the blinking by running on first slide thanks to a reverse playing right?

**Comment by juanmardefago** [comment]
@clementAC I actually implemented a different way of calculating target position, in which the current picture will always be positioned at left: 0, and the other positions for every other picture is calculated based on the picture distance to the current one, the other transitions seem to translate the whole slider-frame based on which picture is the current one, this approach seems to eventually have to "jump" from one end of the slider frame to the other when wrapping around the picture list, and that's what seems to cause the flashing/flickering.

At least that's what I could understand of the original code from the scroll transition mode when I started working on the scroll3d transition mode.

**Comment by nickcooley** [comment]
It probably goes without saying that this issue is exacerbated when using a value of `slidesToShow > 1`.  in my case, I'm showing `1.8` slides with a center `cellAlign` and there's an obvious jump when going from `length` back to `0` or vice-versa...

**Comment by fedriz** [comment]
"nuka-carousel": "^4.5.3"

I'm having the same problem, maybe because it's not a carousel of images.

**Comment by ramasilveyra** [comment]
I was able to find that there is a incoordination between the calculation of the styles of the slides and the slider list that causes the flash.

If you are in a hurry you can use this very nasty hack https://github.com/ramasilveyra/nuka-carousel/commit/0d3553a6f412b01228e2966786170c9607f38cec.

**Comment by johannam999** [comment]
@ramasilveyra Thanks for sharing your solution! We are working on fixing this issue currently.

**Comment by bryanns4grammarly** [comment]
Any solutions?

**Comment by sarmeyer** [comment]
@bryanns4grammarly we believe an unrelated PR #525 fixes this. I will release a patch by the EOD today!

**Comment by bryanns4grammarly** [comment]
Eagerly looking forward to get released today. Please keep me posted

**Comment by clementAC** [comment]
For me the last release fixed the problem. No more blinking 🎉  thank you @sarmeyer and contributors !

**Comment by susheelachoudry** [comment]
I suppose the issue still happens when partial slides are used. Can be replicated by enabling `Toggle Wrap Around` and `Toggle Partial Visible Slides` in the code sandbox demo with the latest release.

Is this related to #527?

**Comment by sarmeyer** [comment]
@susheelachoudry I am unable to reproduce the issue with those factors. Are you able to send me a codesandbox for me to test with? Thanks!

**Comment by halitogunc** [comment]
Same problem is reproducible on version 4.6.5 @sarmeyer. It is still blinking.
https://codesandbox.io/s/dark-cdn-9m1tk
