### ISSUE TITLE
NextButton disables before showing all the slides

### ISSUE THREAD

**Issue by johannam999** [FormidableLabs/nuka-carousel#503]
`NextButton` gets disabled before the last slides are shown. This happens when `cellAlign` prop is set either to `center` or `right` and `slidesToScroll` prop value is more than 1.
Currently in the docs we mentioned that for this feature `cellAlign` `right` or `center` the user needs to set `slidesToScroll` to default( which is 1).

![nukavideo](https://user-images.githubusercontent.com/35988918/52592746-0b884800-2dfc-11e9-9881-75d51963a684.gif)

**Comment by BrittanyIRL** [comment]
Did some research/attempted to fix this but was having trouble finding the root of the issue. Here's what I discovered. 

The surface level issue of this bug is in `src/default-controls` where the switch statement on `nextButtonDisabled` isn't considering any kind of check for an offset for align left.  The secondary issue in that same function is that it's not considering decimals higher than .5 to round up vs rounding down. 
Fixing this math so that the buttons are accurately disabled created an issue with the paging dots, they were multiplying. To handle this I adjusted `src/index` on `nextSlide()` to only return early for cellAlign === left when `this.state.currentSlide > childrenCount...` instead of `>=` since this was causing a one off issue where it was just forever one too early in disabling.  Along with this, the ternary for `nextSlideIndex` on left align was throwing off the ability to use the button to click to the final slid, i found that setting `nextSlideIndex = Math.floor(offset) worked really well. 

I have this branch: bugfix/issue503-nextButton that fixes most of this, but in return the unit tests start to fail. Since this is my first issue in this project I was hesitant to adjust unit tests to fit my 'fix', to me that means I missed something. I'm hoping that leaving this here helps spark someone else's mind with a solution. 

Do feel free to reach out, I'd be happy to discuss this with whoever jumps on it next.
