### ISSUE TITLE
White page when sliding left from index 0 with wraparound = true and 2 slides

### ISSUE THREAD

**Issue by clementdevos** [FormidableLabs/nuka-carousel#606]
Hi, 

I've noticed a bug (visible in the codesandbox demo by the way). 

When you slide left from index 0 with wraparound=true, there is no slide on the left so a blank space is visible until the slide with index 1 appears.

Steps to reproduce :
* https://codesandbox.io/s/04wxloyyp
* Toggle 2 slide
* Toggle wraparound
* slide left

Cheers!

**Comment by sarmeyer** [comment]
Hi @clementdevos thanks for submitting this issue. I can confirm when dragging, there is a flash as the next slide comes into view, this was a known issue before but it was thought to have been fixed. When using the `next` and `prev` buttons, the animation is smooth. I also tested with a slideCount of 3 and it only happens when dragging from the first to the last slide (to the left). The other transitions are smooth. I will spend some time looking into it and of course, welcome help from anyone else who has any ideas how this one popped back up again!

**Comment by dbangerter2** [comment]
This is likely related to the work I did in https://github.com/FormidableLabs/nuka-carousel/pull/600 and the positioning of slides at various values of `direction`.

The fundamental issue is that I _think_ `direction` doesn't get properly set to `1` or `-1` when swiping/dragging, only when clicking. Fixing that would be the true solution, though it might be tricky. An interim solution I can work on sometime this month is splitting the allocation of off-screen slides between both ends of the carousel when the direction is `0`. That would be strictly better and handle the good majority of use cases I think.

**Comment by sarmeyer** [comment]
Fixed in #635 - I will be publishing a release today or tomorrow with this PR included
