### ISSUE TITLE
Infinite render loop if frame.offsetWidth is 0 during an update

### ISSUE THREAD

**Issue by shrugal** [FormidableLabs/nuka-carousel#713]
# Bugs and Questions

### Describe Your Environment

- What version of nuka-carousel are you using: 4.6.7
- What version of React are you using: 16.13.0
- What browser are you using: Chrome 84.0.4147.105
- What machine are you on: Lenovo Yoga C940, Fedora 32, Linux 5.7.10

### Describe the Problem

The combination of `{ autoplay: true, slidesToScroll: "auto", cellSpacing: 0 }` causes an infinite render loop if `frame.offsetWidth` is 0 during `componentDidUpdate` (e.g. from autoplay).

Showing/Hiding the carousel combined with autoplay enabled can cause the update to trigger while the container frame width is 0. This causes `slideWidth` to be 0 as well and `slidesToScroll` to be set to `NaN` in `setDimensions`. This in turn means all equality checks on it fail and that causes an infinite render loop.

**Comment by ilya-uryupov** [comment]
Caught the infinite loop also, but without `autoplay, slidesToScroll or cellSpacing`. It seems that hiding/showing the carousel is enough. Although I'm using it with preact and mobx, which can cause some weirdness.

**Comment by ilya-uryupov** [comment]
Debugged my case and the reasons are `overflow: auto` and scrollbars:
1. initial render
2. image overflows and a vertical scrollbar is added
3. slider recomputes its height to be less than the current
4. in the next render image fits the height without overflow and the scrollbar is removed
5. slider recomputes its height to be greater than the current
6. goto 2.

Created a repro [here](https://codesandbox.io/s/nuka-carousel-infinite-loop-vgh29?file=/index.js).

**Comment by arunpugahz** [comment]
I had this same Infinite render loop but not because of ```{ autoplay: true, slidesToScroll: "auto", cellSpacing: 0 }```
I found out that each Items rendering in the carousel has different heights, Nuka has a piece of code which checks compares the height of the components https://github.com/FormidableLabs/nuka-carousel/blob/b63ca12ab5bfe97266df430a584b40440203e766/src/index.js#L185 which causes rerender again and again.

Solution(This fixed mine):
Try to render the items with fixed height, If your contents exceed that minHeight you can always add overflow: scroll

**Comment by ValGeorgiev** [comment]
This should be fixed in the version 5+. You can install and test it with `npm install nuka-carousel@5.0.3`. Thanks for raising this issue with us.
