### ISSUE TITLE
Unable to preventDefault inside passive event listener invocation

### ISSUE THREAD

**Issue by khmm12** [FormidableLabs/nuka-carousel#732]
# Bug

### Environment

- nuka-carousel 4.7.1
- react 17.0.1, react-dom 17.0.1

### The Problem

React v17 introduced passive listeners for touch events, which can no longer be canceled via `preventDefault`. At best that's annoying warning, at worst that may produce unexpected carousel behaviour.

**Comment by Just-focus** [comment]
i have the same problem

**Comment by finbarmaginn** [comment]
Same here, resulting in hundreds of JS errors but seemingly no affect to UX

**Comment by caycecollins** [comment]
In my case I was noticing some UX performance/jank issues due to the console logging (touch and hold then slowly move the slide left/right).

I created a quick patch (using [patch-package](https://github.com/ds300/patch-package) module) to remove the `e.preventDefault()` call in the `onTouchMove` function:

`patches/nuka-carousel+4.7.4.patch`
```diff
diff --git a/node_modules/nuka-carousel/es/index.js b/node_modules/nuka-carousel/es/index.js
index 0b3a4c5..ca45961 100644
--- a/node_modules/nuka-carousel/es/index.js
+++ b/node_modules/nuka-carousel/es/index.js
@@ -368,7 +368,7 @@ var Carousel = /*#__PURE__*/function (_React$Component) {
           var direction = swipeDirection(_this5.touchObject.startX, e.touches[0].pageX, _this5.touchObject.startY, e.touches[0].pageY, _this5.props.vertical);
 
           if (direction !== 0) {
-            e.preventDefault();
+            // e.preventDefault();
           }
 
           var length = _this5.props.vertical ? Math.round(Math.sqrt(Math.pow(e.touches[0].pageY - _this5.touchObject.startY, 2))) : Math.round(Math.sqrt(Math.pow(e.touches[0].pageX - _this5.touchObject.startX, 2)));
```

**Comment by jcpsimmons** [comment]
@caycecollins I'm having the same issue. I've never used `patch-package` before. Tried `npx patch-package nuka-carousel patches/nuka-carousel+4.7.patch` but no luck - could you provide some insight on how to apply this fix?

**Comment by blopez2010** [comment]
Do we have an ETA regarding this error?

**Comment by sarmeyer** [comment]
Hi all - I'm confused what issues this is causing for people. Could someone provide an example of the error(s) they are seeing and/or a sandbox with the issue present? We might be able to safely remove that `e.preventDefault` but I'd like to understand the initial problem a little better first. Thanks!

**Comment by jcpsimmons** [comment]
@sarmeyer Unable to provide an example from current project but can share the stack trace and detail the behavior a bit more.

- Run slider on React 17
- Every time `onTouchMove` is fired this error logs to the console `Unable to preventDefault inside passive event listener invocation.`
- This happens hundreds of time until the gesture stops, which clogs the console up tons of error messages. 

I suspect this has to do with changes in React 17. Events are now delegated to root instead of the document: https://reactjs.org/blog/2020/10/20/react-v17.html

https://user-images.githubusercontent.com/1920921/108960937-83182100-762b-11eb-80b5-c7b4b1383080.png

**Comment by caycecollins** [comment]
> @caycecollins I'm having the same issue. I've never used `patch-package` before. Tried `npx patch-package nuka-carousel patches/nuka-carousel+4.7.patch` but no luck - could you provide some insight on how to apply this fix?

Did you end up getting this to work? If not:
1. Create a folder in your project's root directory called `patches`
2. Create a new file `nuka-carousel+4.7.4.patch` in the `patches` directory and copy/paste the contents from my previous post. Also, note the `4.7.4` version number... if the source code is the same in previous versions it should work, just adjust the version number in the filename.
3. Run `npx patch-package` without any arguments to apply the patch

If you are using yarn, check the [patch-package](https://github.com/ds300/patch-package) docs, but in short you'll want to also use [postinstall-postinstall](https://github.com/ds300/postinstall-postinstall)

**Comment by gingerrific** [comment]
We can actually repro this directly in the CodeSandbox example.

1. Running in Chrome (v89 at time of writing), visit the CodeSandbox [example](https://codesandbox.io/s/silly-rhodes-5pr2i?fontsize=14&hidenavigation=1&theme=dark).
2. Ensure `react` and `react-dom` are versioned at "^17.0.0"
<img width="261" alt="Screen Shot 2021-03-12 at 1 09 27 PM" src="https://user-images.githubusercontent.com/7433825/111001378-881de580-8338-11eb-9f46-fe53c7c9f158.png">. 
3. Open DevTools and Toggle the Device Toolbar and select "Responsive" or any mobile device from the list
4. Click and drag the first slide and observe the console - which will look a lot like @jcpsimmons' example X however long you hold the drag for.

After a bit more digging it kind of seems like there are 2 options:
1. remove the `e.preventDefault` from the `onTouchMove` handler
2. add a `ref` to the relevant `div` and manually attach the event listener and include the option: `{ passive: false }`

Either option is viable, but the first is certainly easier and seems to cover most scenarios. I've been unable to reproduce any unexpected behavior after simply removing the `preventDefault` call in the `onTouchMove`. It seems like this may have been a vestige of mimicking the `onMouseDown` behavior and not actually necessary all along. We need the `preventDefault` in the click handler to prevent dragging the image in browsers (Safari), but that's ok as pointer events are handled differently and won't cause the console warning related to the passive events.

@caycecollins you called out:
>This could cause undesired behavior if you have element(s) under the slide element (with the touch handler) that you don't want users to touch/accidentally trigger. 

Do you mean that this could cause issues with existing users where they didn't know that their child elements may have been having touch actions blocked by this existing `preventDefault`, or that there are example use cases where it would be expected/desired that the Carousel retain this `preventDefault`? I personally wasn't able to come up with any for the latter, but definitely interested to hear if you or others know otherwise

**Comment by sarmeyer** [comment]
FYI the fix for this (removing preventDefault from the touch event handler) has been released with v4.7.6

**Comment by jcpsimmons** [comment]
@sarmeyer Awesome thanks so much 🙏

**Comment by khmm12** [comment]
Then I can close the issue 👍
