### ISSUE TITLE
Support `vw` and `vh` based values for `initialSlideWidth` and `initialSlideHeight` props for a better server-side rendering support

### ISSUE THREAD

**Issue by manojVivek** [FormidableLabs/nuka-carousel#786]
# Feature Request

### Describe the Problem
This is a request to add support for `vw` and `vh` based values for `initialSlideWidth` and `initialSlideHeight` props. 

### Background
The pixel-based value for `initialSlideWidth` and `initialSlideHeight` props is a real blocker for server-side rendered applications that too when implementing custom designs that vary based on the user's device viewport. 

### Suggested Approach
Looking at the current implementation where the slides are absolutely positioned, it makes sense why a `%` based value cannot be accepted. But we can mitigate this constraint by making use of the `vw`/`vh` based values combined with CSS `calc` for the styles. 

I was taking a peek at the code and in the newly suggested approach the following code to calculate the position of a slide can be re-written something like the snippet below that.

**Current Implementation**:

https://github.com/FormidableLabs/nuka-carousel/blob/5812a3ca6609e6d7db021f6abcf69ef21bb5d7e5/src/transitions/scroll-transition.js#L61-L63

**New Implementation**:
```js
let targetPosition = 
  `calc( ${currentSlideIndex} * ${this.props.slideWidth} + ${this.props.cellSpacing}px)`;
```

I have manually tried this on an existing app by modifying the `style` attribute on the dom and it worked fine, so just wanted to get your thoughts here. 

I could be missing something very obvious here, but just wanted to put this idea out and discuss it. 😅

**Comment by ivansky** [comment]
At least it should not set width = 0 for slide because it cannot calculate it on server,
It does not make any sense.

**Comment by ValGeorgiev** [comment]
Hey @manojVivek, thanks for raising this with us. I did some tests these days and tried different approaches with vh and vw. Unfortunately there is no easy fix for this with the current architecture and the main reason for this is the absolute positioning. The main reason to have `initialSlideWidth` and `initialSlideHeight` is because of position: absolute, so we can have some width/height until the client js kicks in. If we apply your suggestion with vw on the SSR is going to work in some cases, but the issue with the height will remain, the browser will set height 0 of relative container with absolute children. 

I am thinking of migrating out of position absolute approach and usage of width and translate. But this will be a long term goal. 

Feel free to suggest any improvement or even do a PR, I will be happy to help with testing and etc.

**Comment by manojVivek** [comment]
@ValGeorgiev Yeah, I agree. I tried as well, with the current architecture, it is too hard to accommodate `vw`/`vh` based values for the `initialSlideWidth` and `initialSlideHeight`.

It is good to know that there are plans to migrate the architecture. Please let me know if we track that work in some place, I would like to contribute to the code/idea. The library should focus on allowing native `CSS` units for the dimensions, to offer better `SSR` support.

**Comment by ValGeorgiev** [comment]
@manojVivek we are on the same page here. I will create a separate ticket and will try to summarise what needs to be done for migrating out of position absolute. Thanks for your collaboration so far!

**Comment by ValGeorgiev** [comment]
@manojVivek This is fixed in v5 and released. Thank you for raising this issue with us. I will close it now, feel free to reopen it or raise another if you have questions or found an issue
