### ISSUE TITLE
[v6] Add new property which stops autoplay when user interacts with carousel buttons

### ISSUE THREAD

**Issue by gksander** [FormidableLabs/nuka-carousel#918]
Add a carousel prop that will cancel autoplay when user interacts with carousel controls.

**Comment by fritz-c** [comment]
Related: #499

**Comment by fritz-c** [comment]
I'm in the process of [adding an `onUserNavigation` callback](https://github.com/FormidableLabs/nuka-carousel/compare/feat/default-controls-onclick-handlers) that would make this behavior easily achievable while allowing for a bit more flexibility in exactly how the autoplay stops and starts. For example, rather than disabling autoplay completely, they could merely set a longer `autoplayInterval` temporarily, so autoplay eventually resumes.
