### ISSUE TITLE
`disableEdgeSwiping` prevents successive forward swipes

### ISSUE THREAD

**Issue by mpedersen15** [FormidableLabs/nuka-carousel#942]
# Bugs and Questions

### Prerequisites

**Feel free to delete this section if you have checked off all of the following.**

- [x] I've searched open [issues](https://github.com/FormidableLabs/nuka-carousel/issues) to make sure I'm not opening a duplicate issue
- [x] I have read through the docs before asking a question
- [x] I am using the latest version of nuka-carousel

### Describe Your Environment

- What version of nuka-carousel are you using? **5.2.0**
- What version of React are you using? **18.0.0**
- What browser are you using? **Chrome Version 103.0.5060.114**

### Describe the Problem

It seems like the `disableEdgeSwiping` is preventing successive swiping forward after the *first* swipe forward. Swiping backwards works successively however. 

I've produced [a minimal reproduction at this codesandbox](https://codesandbox.io/s/distracted-flower-ni2hsj?file=/src/App.js)

**Expected behavior:** [What you expect to happen]
In a carousel with 3 or more slides, after swiping from slide 1 to slide 2, I should be able to immediately swipe from slide 2 to slide 3.

**Actual behavior:** [What actually happens]
In a carousel with 3 or more slides, after swiping from slide 1 to slide 2, I am not able to continue swiping forward. Swiping backwards and using the dots or side "Prev"/"Next" buttons works as expected (and is the only way to navigate to slide 3). 

### Additional Information
The bug was NOT present in `nuka-carousel` v4.7.4 (the previous version I was using in my project)

Thank you all for an awesome carousel component! If I missed anything on this issue, I apologize and will fix it!

**Comment by fritz-c** [comment]
Thank you for creating the issue and the minimal reproduction sandbox. Indeed, this does look like a bug. We have a few yet-unreleased [bugfixes that can be seen in action on the demo site](https://nuka-carousel-next.vercel.app/?slides=4&params=%7B%22disableEdgeSwiping%22:true,%22slidesToShow%22:3%7D).

Does this better represent the behavior you expect?

It does not match your described "expected behavior" in that it avoids showing whitespace to the right and therefore only has two locations it can scroll through to start with, but the UI is at least consistent in its treatment of where the end of the carousel is.

This change was made to be more consistent with the treatment of the `slidesToScroll > 1 && slidesToShow > 1` case, where it sought to avoid showing whitespace at the end ([demo of this with the existing library version, based on your sandbox](https://codesandbox.io/s/nuka-carousel-playground-forked-8rxk72)).

We don't have a concrete date in mind for releasing the next version, but just let me know if this fix is what you had in mind.

**Comment by mpedersen15** [comment]
Thank you for the thorough explanation @fritz-c ! I understand now that the lack of scrolling in my demo/sandbox was due to the last slide in the carousel already being visible. I do think that the demo site version (only show TWO dot indicators) is a step in the right direction! Showing more dot indicators than are scrollable (as in my sandbox) is definitely confusing.

**Comment by fritz-c** [comment]
This is now fixed in v5.3.0
